apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ledger.fullname" . }}
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.ledger.adminPassword -}}
  ledger-admin-password: {{ .Values.ledger.adminPassword | b64enc | quote }}
  {{ else -}}
  ledger-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end -}}