{{- $k8sVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- range .Values.proxy -}}
{{- $proxy := . -}}
{{- $name := .name -}}
{{- $service := .service -}}
{{- with .ingress -}}
---
{{- if semverCompare ">=1.14-0" $k8sVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $name }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .tls }}
  tls:
    {{- toYaml .tls | nindent 4 }}
{{- end }}
  rules:
  {{- $paths := .paths -}}
  {{- range .hosts }}
  - host: {{ . }}
    http:
      paths:
      {{- range $paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $name }}
          servicePort: {{ $service.port }}
      {{ end }}
  {{- end }}
{{- end }}
{{- end }}