{{- $servicePort := .Values.service.port -}}
{{- range .Values.proxy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  ports:
    - protocol: TCP
      port: {{ $servicePort }}
      targetPort: {{ .backend.port }}
{{- end }}